services:
  database:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
        POSTGRES_PASSWORD: postgres
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080